In [66]:
import pandas as pd
!pip install missingno
import missingno as msno
import matplotlib.pyplot as plt

Requirement already satisfied: missingno in /usr/local/lib/python3.11/dist-packages (0.5.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from missingno) (1.26.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from missingno) (3.10.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from missingno) (1.13.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (from missingno) (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (2.8.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.11/dist-packages (from seaborn->missingno) (2.2.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->seaborn->missingno) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->seaborn->missingno) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->missingno) (1.17.0)

# Data Collection

Importo dataset

In [51]:
!wget https://github.com/pablolube/No-Country/raw/refs/heads/main/data/data_limpia/Fechas%20corregidas.xlsx
df_fechas = pd.read_excel('Fechas corregidas.xlsx')

--2025-01-21 01:00:02--  https://github.com/pablolube/No-Country/raw/refs/heads/main/data/data_limpia/Fechas%20corregidas.xlsx
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/pablolube/No-Country/refs/heads/main/data/data_limpia/Fechas%20corregidas.xlsx [following]
--2025-01-21 01:00:02--  https://raw.githubusercontent.com/pablolube/No-Country/refs/heads/main/data/data_limpia/Fechas%20corregidas.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 295655 (289K) [application/octet-stream]
Saving to: ‘Fechas corregidas.xlsx.14’

Fechas corregidas.x 100%[===================>] 288.73K  --.-KB/s    in 0.03s

2025-01-21 01:00:02 (9.80 MB/s) - ‘Fechas corregidas.xlsx.14’ saved [295655/295655]

El  dataset disponía de errores con las fechas, por lo que decidí corregirlo con Power Query, por lo cual importo fechas corregidas

In [52]:
!wget  https://github.com/pablolube/No-Country/raw/refs/heads/main/data/raw/HDHI%20Admission%20data.csv
df = pd.read_csv('HDHI Admission data.csv')
df

--2025-01-21 01:00:03--  https://github.com/pablolube/No-Country/raw/refs/heads/main/data/raw/HDHI%20Admission%20data.csv
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/pablolube/No-Country/refs/heads/main/data/raw/HDHI%20Admission%20data.csv [following]
--2025-01-21 01:00:04--  https://raw.githubusercontent.com/pablolube/No-Country/refs/heads/main/data/raw/HDHI%20Admission%20data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2600930 (2.5M) [text/plain]
Saving to: ‘HDHI Admission data.csv.12’

HDHI Admission data 100%[===================>]   2.48M  --.-KB/s    in 0.06s

2025-01-21 01:00:04 (43.8 MB/s) - ‘HDHI Admission data.csv.12’ saved [2600930/2600930]

,SNO,MRD No.,D.O.A,D.O.D,AGE,GENDER,RURAL,TYPE OF ADMISSION-EMERGENCY/OPD,month year,DURATION OF STAY,...,CONGENITAL,UTI,NEURO CARDIOGENIC SYNCOPE,ORTHOSTATIC,INFECTIVE ENDOCARDITIS,DVT,CARDIOGENIC SHOCK,SHOCK,PULMONARY EMBOLISM,CHEST INFECTION
0,1,234735,4/1/2017,4/3/2017,81,M,R,E,Apr-17,3,...,0,0,0,0,0,0,0,0,0,0
1,2,234696,4/1/2017,4/5/2017,65,M,R,E,Apr-17,5,...,0,0,0,0,0,0,0,0,0,0
2,3,234882,4/1/2017,4/3/2017,53,M,U,E,Apr-17,3,...,0,0,0,0,0,0,0,0,0,0
3,4,234635,4/1/2017,4/8/2017,67,F,U,E,Apr-17,8,...,0,0,0,0,0,0,0,0,0,0
4,5,234486,4/1/2017,4/23/2017,60,F,U,E,Apr-17,23,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15752,15753,699585,31/03/2019,04/04/2019,86,F,U,O,Mar-19,5,...,0,0,0,0,0,0,0,0,0,0
15753,15754,699500,3/31/2019,4/1/2019,50,M,R,E,Mar-19,2,...,0,0,0,0,0,0,0,0,0,0
15754,15755,700415,31/03/2019,09/04/2019,82,M,U,E,Mar-19,10,...,0,0,0,0,0,0,0,0,0,0
15755,15756,699524,31/03/2019,03/04/2019,59,F,U,O,Mar-19,4,...,0,0,0,0,0,0,0,0,0,0
15756,15757,699524,31/03/2019,03/04/2019,59,F,U,O,Mar-19,4,...,0,0,0,0,0,0,0,0,0,0

Realizo un Merge con el Dataset

In [53]:

df = df.merge(
    df_fechas,
    left_on='SNO',
    right_on='SRO',
    how='left',
    suffixes=('', '_2')  # Agrega sufijos para evitar conflictos de nombres
)

Borro aquellas fechas erroneas

In [54]:
df=df.drop(columns=['D.O.A','D.O.D','SRO'])
df.rename(columns={'Fecha de Admision': 'D.O.A', 'Fecha de Alta': 'D.O.D'}, inplace=True)

Reviso las columnas de mi dataset

Traduzco variables y cambio abreviaciones por los metadatos

In [55]:
# Traduzco Variables
rename_dict = {'MRD No.': 'ID','SNO': 'ADMISION',
     'D.O.A': 'Fecha de Admisión',
    'D.O.D': 'Fecha de Alta',
    'AGE': 'Edad',
    'GENDER': 'Género',
    'RURAL': 'Residencia',
    'TYPE OF ADMISSION-EMERGENCY/OPD': 'Tipo de Admisión',
    'month year': 'Mes-Año',
    'DURATION OF STAY': 'Duración Estadia',
    'duration of intensive unit stay': 'Duración Estadia unidad intensiva',
    'OUTCOME': 'Motivo de Alta',
    'SMOKING ': 'Fumador',
    'ALCOHOL': 'Alcohol',
    'DM': 'Diabetes Mellitus',
    'HTN': 'Hipertensión',
    'CAD': 'Enfermedad Coronaria Arterial',
    'PRIOR CMP': 'Miocardiopatía',
    'CKD': 'Enfermedad Renal Crónica',
    'HB': 'Hemoglobina',
    'TLC': 'Leucocitos',
    'PLATELETS': 'Plaquetas',
    'GLUCOSE': 'Glucosa',
    'UREA': 'Urea',
    'CREATININE': 'Creatinina',
    'BNP': 'Péptido Natriurético Tipo B',
    'RAISED CARDIAC ENZYMES': 'Enzimas Cardiacas Elevadas',
    'EF': 'Fracción de Eyección',
    'SEVERE ANAEMIA': 'Anemia Severa',
    'ANAEMIA': 'Anemia',
    'STABLE ANGINA': 'Angina Estable',
    'ACS': 'Síndrome Coronario Agudo',
    'STEMI': 'Infarto de Miocardio(STEMI)',
    'ATYPICAL CHEST PAIN': 'Dolor Torácico Atípico',
    'HEART FAILURE': 'Insuficiencia Cardíaca',
    'HFREF': 'Insuficiencia Cardíaca con Fracción de Eyección Reducida',
    'HFNEF': 'Insuficiencia Cardíaca con Fracción de Eyección Normal',
    'VALVULAR': 'Enfermedad Valvular Cardíaca',
    'CHB': 'Bloqueo Cardíaco Completo',
    'SSS': 'Síndrome del Nodo Sinusal Enfermo',
    'AKI': 'Lesión Renal Aguda',
    'CVA INFRACT': 'Accidente Cerebrovascular Isquémico',
    'CVA BLEED': 'Accidente Cerebrovascular Hemorrágico',
    'AF': 'Fibrilación Auricular',
    'VT': 'Taquicardia Ventricular',
    'PSVT': 'Taquicardia Supraventricular Paroxística',
    'CONGENITAL': 'Cardiopatía Congénita',
    'UTI': 'Infección del Tracto Urinario',
    'NEURO CARDIOGENIC SYNCOPE': 'Síncope Neurocardiogénico',
    'ORTHOSTATIC': 'Ortostático',
    'INFECTIVE ENDOCARDITIS': 'Endocarditis Infecciosa',
    'DVT': 'Trombosis Venosa Profunda',
    'CARDIOGENIC SHOCK': 'Choque Cardiogénico',
    'SHOCK': 'Shock',
    'PULMONARY EMBOLISM': 'Embolia Pulmonar',
    'CHEST INFECTION': 'Infección Torácica'
}

# Renombrar columnas
df.rename(columns=rename_dict, inplace=True)

In [56]:
df

,ADMISION,ID,Edad,Género,Residencia,Tipo de Admisión,Mes-Año,Duración Estadia,Duración Estadia unidad intensiva,Motivo de Alta,...,Síncope Neurocardiogénico,Ortostático,Endocarditis Infecciosa,Trombosis Venosa Profunda,Choque Cardiogénico,Shock,Embolia Pulmonar,Infección Torácica,Fecha de Admisión,Fecha de Alta
0,1,234735,81,M,R,E,Apr-17,3,2,DISCHARGE,...,0,0,0,0,0,0,0,0,2017-04-01,2017-04-03
1,2,234696,65,M,R,E,Apr-17,5,2,DISCHARGE,...,0,0,0,0,0,0,0,0,2017-04-01,2017-04-05
2,3,234882,53,M,U,E,Apr-17,3,3,DISCHARGE,...,0,0,0,0,0,0,0,0,2017-04-01,2017-04-03
3,4,234635,67,F,U,E,Apr-17,8,6,DISCHARGE,...,0,0,0,0,0,0,0,0,2017-04-01,2017-04-08
4,5,234486,60,F,U,E,Apr-17,23,9,DISCHARGE,...,0,0,0,0,0,0,0,0,2017-04-01,2017-04-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15752,15753,699585,86,F,U,O,Mar-19,5,1,DISCHARGE,...,0,0,0,0,0,0,0,0,2019-03-31,2019-04-04
15753,15754,699500,50,M,R,E,Mar-19,2,2,EXPIRY,...,0,0,0,0,0,0,0,0,2019-03-31,2019-04-01
15754,15755,700415,82,M,U,E,Mar-19,10,5,DISCHARGE,...,0,0,0,0,0,0,0,0,2019-03-31,2019-04-09
15755,15756,699524,59,F,U,O,Mar-19,4,2,DISCHARGE,...,0,0,0,0,0,0,0,0,2019-03-31,2019-04-03
15756,15757,699524,59,F,U,O,Mar-19,4,2,DISCHARGE,...,0,0,0,0,0,0,0,0,2019-03-31,2019-04-03

#Data Wrangling

In [57]:
# Replace values
df['Género'] = df['Género'].replace({'M': 'Masculino', 'F': 'Femenino'})
df['Tipo de Admisión'] = df['Tipo de Admisión'].replace({'E': 'Emergencia', 'O': 'Ambulatorio'})
df['Motivo de Alta'] = df['Motivo de Alta'].replace({'DISCHARGE': 'Alta', 'EXPIRY': 'Fallecimiento', 'DAMA': 'Alta contra recomendación médica'})
df['Residencia'] = df['Residencia'].replace({'R': 'Rural', 'U': 'Urbano'})
df

,ADMISION,ID,Edad,Género,Residencia,Tipo de Admisión,Mes-Año,Duración Estadia,Duración Estadia unidad intensiva,Motivo de Alta,...,Síncope Neurocardiogénico,Ortostático,Endocarditis Infecciosa,Trombosis Venosa Profunda,Choque Cardiogénico,Shock,Embolia Pulmonar,Infección Torácica,Fecha de Admisión,Fecha de Alta
0,1,234735,81,Masculino,Rural,Emergencia,Apr-17,3,2,Alta,...,0,0,0,0,0,0,0,0,2017-04-01,2017-04-03
1,2,234696,65,Masculino,Rural,Emergencia,Apr-17,5,2,Alta,...,0,0,0,0,0,0,0,0,2017-04-01,2017-04-05
2,3,234882,53,Masculino,Urbano,Emergencia,Apr-17,3,3,Alta,...,0,0,0,0,0,0,0,0,2017-04-01,2017-04-03
3,4,234635,67,Femenino,Urbano,Emergencia,Apr-17,8,6,Alta,...,0,0,0,0,0,0,0,0,2017-04-01,2017-04-08
4,5,234486,60,Femenino,Urbano,Emergencia,Apr-17,23,9,Alta,...,0,0,0,0,0,0,0,0,2017-04-01,2017-04-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15752,15753,699585,86,Femenino,Urbano,Ambulatorio,Mar-19,5,1,Alta,...,0,0,0,0,0,0,0,0,2019-03-31,2019-04-04
15753,15754,699500,50,Masculino,Rural,Emergencia,Mar-19,2,2,Fallecimiento,...,0,0,0,0,0,0,0,0,2019-03-31,2019-04-01
15754,15755,700415,82,Masculino,Urbano,Emergencia,Mar-19,10,5,Alta,...,0,0,0,0,0,0,0,0,2019-03-31,2019-04-09
15755,15756,699524,59,Femenino,Urbano,Ambulatorio,Mar-19,4,2,Alta,...,0,0,0,0,0,0,0,0,2019-03-31,2019-04-03
15756,15757,699524,59,Femenino,Urbano,Ambulatorio,Mar-19,4,2,Alta,...,0,0,0,0,0,0,0,0,2019-03-31,2019-04-03

In [58]:
df.shape

(15757, 56)

In [ ]:
# prompt: transforacion de tipo dedatos ejemplos

# ... (Your existing code)

# Example 1: Convert 'Edad' (which seems to be numeric) to integer
df['Edad'] = df['Edad'].astype(int)

# Example 2: Convert 'Fecha de Admisión' and 'Fecha de Alta' to datetime objects
df['Fecha de Admisión'] = pd.to_datetime(df['Fecha de Admisión'])
df['Fecha de Alta'] = pd.to_datetime(df['Fecha de Alta'])

# Example 3: Convert 'Duración Estadia' to numeric, handling potential errors
df['Duración Estadia'] = pd.to_numeric(df['Duración Estadia'], errors='coerce')  # Coerce invalid values to NaN

# Example 4: Convert boolean columns to integer (0 or 1)
boolean_columns = ['Fumador', 'Alcohol', 'Diabetes Mellitus', 'Hipertensión',
                   'Enfermedad Coronaria Arterial', 'Miocardiopatía', 'Enfermedad Renal Crónica',
                   'Anemia Severa', 'Anemia', 'Angina Estable', 'Síndrome Coronario Agudo',
                   'Infarto de Miocardio(STEMI)', 'Dolor Torácico Atípico', 'Insuficiencia Cardíaca',
                   'Insuficiencia Cardíaca con Fracción de Eyección Reducida',
                   'Insuficiencia Cardíaca con Fracción de Eyección Normal',
                   'Enfermedad Valvular Cardíaca', 'Bloqueo Cardíaco Completo',
                   'Síndrome del Nodo Sinusal Enfermo', 'Lesión Renal Aguda',
                   'Accidente Cerebrovascular Isquémico', 'Accidente Cerebrovascular Hemorrágico',
                   'Fibrilación Auricular', 'Taquicardia Ventricular',
                   'Taquicardia Supraventricular Paroxística', 'Cardiopatía Congénita',
                   'Infección del Tracto Urinario', 'Síncope Neurocardiogénico',
                   'Ortostático', 'Endocarditis Infecciosa', 'Trombosis Venosa Profunda',
                   'Choque Cardiogénico', 'Shock', 'Embolia Pulmonar', 'Infección Torácica',
                   'Enzimas Cardiacas Elevadas']


for col in boolean_columns:
    df[col] = df[col].astype(int)

# Example 5:  Convert 'Mes-Año' to datetime (assuming it's in a consistent format)
# You might need to adjust the format string depending on your data
df['Mes-Año'] = pd.to_datetime(df['Mes-Año'], format='%b %Y', errors='coerce')


# Display the data types of the updated DataFrame
df.dtypes

# ... (rest of your code)

Transformó los tipos de datos

In [ ]:
# prompt: dejar esto todo como comentado # prompt: transformar columna Id a un dato tipo integer
# df = df.astype({
#     'ID': 'int',
#     'Género': 'string',
#     'Residencia': 'string',
#     'Tipo de Admisión': 'string',
#     'Motivo de Alta': 'string'
#    })
# df['Fecha de Admisión'] = pd.to_datetime(df['Fecha de Admisión']).dt.date
# df['Fecha de Alta'] = pd.to_datetime(df['Fecha de Alta']).dt.date

# Convert 'ID' column to integer, handling potential errors
# df['ID'] = pd.to_numeric(df['ID'], errors='coerce').astype('Int64') # Use 'Int64' to allow for NaN values

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15757 entries, 0 to 15756
Data columns (total 56 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   ADMISION                                                  15757 non-null  int64
 1   ID                                                        15757 non-null  object
 2   Edad                                                      15757 non-null  int64
 3   Género                                                    15757 non-null  object
 4   Residencia                                                15757 non-null  object
 5   Tipo de Admisión                                          15757 non-null  object
 6   Mes-Año                                                   15757 non-null  object
 7   Duración Estadia                                          15757 non-null  int64
 8   Duración Estadia unidad intensiva                         15757 non-null  int64
 9   Motivo de Alta                                            15757 non-null  object
 10  Fumador                                                   15757 non-null  int64
 11  Alcohol                                                   15757 non-null  int64
 12  Diabetes Mellitus                                         15757 non-null  int64
 13  Hipertensión                                              15757 non-null  int64
 14  Enfermedad Coronaria Arterial                             15757 non-null  int64
 15  Miocardiopatía                                            15757 non-null  int64
 16  Enfermedad Renal Crónica                                  15757 non-null  int64
 17  Hemoglobina                                               15505 non-null  object
 18  Leucocitos                                                15471 non-null  object
 19  Plaquetas                                                 15472 non-null  object
 20  Glucosa                                                   14894 non-null  object
 21  Urea                                                      15516 non-null  object
 22  Creatinina                                                15510 non-null  object
 23  Péptido Natriurético Tipo B                               7316 non-null   object
 24  Enzimas Cardiacas Elevadas                                15757 non-null  int64
 25  Fracción de Eyección                                      14252 non-null  object
 26  Anemia Severa                                             15757 non-null  int64
 27  Anemia                                                    15757 non-null  int64
 28  Angina Estable                                            15757 non-null  int64
 29  Síndrome Coronario Agudo                                  15757 non-null  int64
 30  Infarto de Miocardio(STEMI)                               15757 non-null  int64
 31  Dolor Torácico Atípico                                    15757 non-null  int64
 32  Insuficiencia Cardíaca                                    15757 non-null  int64
 33  Insuficiencia Cardíaca con Fracción de Eyección Reducida  15757 non-null  int64
 34  Insuficiencia Cardíaca con Fracción de Eyección Normal    15757 non-null  int64
 35  Enfermedad Valvular Cardíaca                              15757 non-null  int64
 36  Bloqueo Cardíaco Completo                                 15757 non-null  int64
 37  Síndrome del Nodo Sinusal Enfermo                         15757 non-null  int64
 38  Lesión Renal Aguda                                        15757 non-null  int64
 39  Accidente Cerebrovascular Isquémico                       15757 non-null  int64
 40  Accidente Cerebrovascular Hemorrágico                     15757 non-null  int64
 41  Fibrilación Auricular                                     15757 non-null  int64
 42  Taquicardia Ventricular                                   15757 non-null  int64
 43  Taquicardia Supraventricular Paroxística                  15757 non-null  int64
 44  Cardiopatía Congénita                                     15757 non-null  int64
 45  Infección del Tracto Urinario                             15757 non-null  int64
 46  Síncope Neurocardiogénico                                 15757 non-null  int64
 47  Ortostático                                               15757 non-null  int64
 48  Endocarditis Infecciosa                                   15757 non-null  int64
 49  Trombosis Venosa Profunda                                 15757 non-null  int64
 50  Choque Cardiogénico                                       15757 non-null  int64
 51  Shock                                                     15757 non-null  int64
 52  Embolia Pulmonar                                          15757 non-null  int64
 53  Infección Torácica                                        15757 non-null  object
 54  Fecha de Admisión                                         15757 non-null  datetime64[ns]
 55  Fecha de Alta                                             15757 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(39), object(15)
memory usage: 6.7+ MB

In [88]:
print("COLUMNAS CON DATOS NULOS Y SU CONTEO")
print(df.isnull().sum()[df.isnull().sum() > 0])

COLUMNAS CON DATOS NULOS Y SU CONTEO
Hemoglobina                     252
Leucocitos                      286
Plaquetas                       285
Glucosa                         863
Urea                            241
Creatinina                      247
Péptido Natriurético Tipo B    8441
Fracción de Eyección           1505
dtype: int64

Los nulos corresponden solo a los estudios Médicos, lo que significa que no a todas las personas se le hacen estudios de sangre

In [92]:
# Convert 'Fecha de Admisión' and 'Fecha de Alta' to datetime objects without time information
df['Fecha de Admisión'] = pd.to_datetime(df['Fecha de Admisión']).dt.date
df['Fecha de Alta'] = pd.to_datetime(df['Fecha de Alta']).dt.date

In [90]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ADMISION,15757.0,7879.000000,4548.798431,1.0,3940.0,7879.0,11818.0,15757.0
Edad,15757.0,61.426160,13.420862,4.0,54.0,62.0,70.0,110.0
Duración Estadia,15757.0,6.415054,5.011421,1.0,3.0,5.0,8.0,98.0
Duración Estadia unidad intensiva,15757.0,3.803770,4.015640,0.0,1.0,3.0,5.0,58.0
Fumador,15757.0,0.050327,0.218625,0.0,0.0,0.0,0.0,1.0
Alcohol,15757.0,0.064797,0.246174,0.0,0.0,0.0,0.0,1.0
Diabetes Mellitus,15757.0,0.323475,0.467817,0.0,0.0,0.0,1.0,1.0
Hipertensión,15757.0,0.485879,0.499816,0.0,0.0,0.0,1.0,1.0
Enfermedad Coronaria Arterial,15757.0,0.669607,0.470369,0.0,0.0,1.0,1.0,1.0
Miocardiopatía,15757.0,0.154471,0.361411,0.0,0.0,0.0,0.0,1.0
Enfermedad Renal Crónica,15757.0,0.098369,0.297822,0.0,0.0,0.0,0.0,1.0
Enzimas Cardiacas Elevadas,15757.0,0.198134,0.398606,0.0,0.0,0.0,0.0,1.0
Anemia Severa,15757.0,0.019356,0.137779,0.0,0.0,0.0,0.0,1.0
Anemia,15757.0,0.176874,0.381574,0.0,0.0,0.0,0.0,1.0
Angina Estable,15757.0,0.081805,0.274076,0.0,0.0,0.0,0.0,1.0
Síndrome Coronario Agudo,15757.0,0.365742,0.481653,0.0,0.0,0.0,1.0,1.0
Infarto de Miocardio(STEMI),15757.0,0.139747,0.346736,0.0,0.0,0.0,0.0,1.0
Dolor Torácico Atípico,15757.0,0.025576,0.157871,0.0,0.0,0.0,0.0,1.0
Insuficiencia Cardíaca,15757.0,0.289459,0.453526,0.0,0.0,0.0,1.0,1.0
Insuficiencia Cardíaca con Fracción de Eyección Reducida,15757.0,0.153646,0.360621,0.0,0.0,0.0,0.0,1.0
Insuficiencia Cardíaca con Fracción de Eyección Normal,15757.0,0.136574,0.343408,0.0,0.0,0.0,0.0,1.0
Enfermedad Valvular Cardíaca,15757.0,0.035032,0.183867,0.0,0.0,0.0,0.0,1.0
Bloqueo Cardíaco Completo,15757.0,0.026147,0.159578,0.0,0.0,0.0,0.0,1.0
Síndrome del Nodo Sinusal Enfermo,15757.0,0.006791,0.082128,0.0,0.0,0.0,0.0,1.0
Lesión Renal Aguda,15757.0,0.222377,0.415857,0.0,0.0,0.0,0.0,1.0
Accidente Cerebrovascular Isquémico,15757.0,0.029447,0.169062,0.0,0.0,0.0,0.0,1.0
Accidente Cerebrovascular Hemorrágico,15757.0,0.004252,0.065071,0.0,0.0,0.0,0.0,1.0
Fibrilación Auricular,15757.0,0.050771,0.219537,0.0,0.0,0.0,0.0,1.0
Taquicardia Ventricular,15757.0,0.032938,0.178479,0.0,0.0,0.0,0.0,1.0
Taquicardia Supraventricular Paroxística,15757.0,0.007552,0.086577,0.0,0.0,0.0,0.0,1.0
Cardiopatía Congénita,15757.0,0.010472,0.101797,0.0,0.0,0.0,0.0,1.0
Infección del Tracto Urinario,15757.0,0.061877,0.240940,0.0,0.0,0.0,0.0,1.0
Síncope Neurocardiogénico,15757.0,0.008377,0.091146,0.0,0.0,0.0,0.0,1.0
Ortostático,15757.0,0.007870,0.088363,0.0,0.0,0.0,0.0,1.0
Endocarditis Infecciosa,15757.0,0.001840,0.042862,0.0,0.0,0.0,0.0,1.0
Trombosis Venosa Profunda,15757.0,0.013264,0.114406,0.0,0.0,0.0,0.0,1.0
Choque Cardiogénico,15757.0,0.059910,0.237327,0.0,0.0,0.0,0.0,1.0
Shock,15757.0,0.046646,0.210886,0.0,0.0,0.0,0.0,1.0
Embolia Pulmonar,15757.0,0.015358,0.122977,0.0,0.0,0.0,0.0,1.0

Calculo el reingreso

In [93]:
df.sort_index
df['Nro de Ingresos'] = df.groupby('ID').cumcount() + 1

Reviso la cantidad de persona que ingresaron más de una vez

In [94]:
df.sort_values(by='ID')
df[df['Nro de Ingresos']>=2]

,ADMISION,ID,Edad,Género,Residencia,Tipo de Admisión,Mes-Año,Duración Estadia,Duración Estadia unidad intensiva,Motivo de Alta,...,Ortostático,Endocarditis Infecciosa,Trombosis Venosa Profunda,Choque Cardiogénico,Shock,Embolia Pulmonar,Infección Torácica,Fecha de Admisión,Fecha de Alta,Nro de Ingresos
16,17,413903,54,Masculino,Urbano,Ambulatorio,Apr-17,3,1,Alta,...,0,0,0,0,0,0,0,2017-04-01,2017-04-03,2
90,91,382159,47,Femenino,Urbano,Emergencia,Apr-17,6,1,Alta,...,0,0,0,0,0,0,0,2017-04-04,2017-04-09,2
95,96,48098,65,Femenino,Rural,Ambulatorio,Apr-17,6,4,Alta,...,0,0,0,1,1,0,0,2017-04-05,2017-04-10,2
130,131,384232,80,Femenino,Urbano,Emergencia,Apr-17,5,5,Alta,...,0,0,0,0,0,0,0,2017-04-08,2017-04-12,2
147,148,203622,58,Femenino,Urbano,Ambulatorio,Apr-17,8,0,Alta,...,0,0,0,0,0,0,0,2017-04-10,2017-04-17,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15743,15744,699413,75,Femenino,Urbano,Emergencia,Mar-19,4,3,Alta,...,0,0,0,0,0,0,0,2019-03-30,2019-04-02,2
15745,15746,699480,60,Femenino,Urbano,Emergencia,Mar-19,5,4,Alta contra recomendación médica,...,0,0,0,0,0,0,0,2019-03-30,2019-04-03,2
15748,15749,273016,74,Femenino,Urbano,Emergencia,Mar-19,2,2,Alta,...,0,0,0,0,0,0,0,2019-03-30,2019-03-31,15
15751,15752,469963,60,Femenino,Urbano,Emergencia,Mar-19,9,9,Alta,...,0,0,0,0,0,0,0,2019-03-31,2019-04-08,2
15756,15757,699524,59,Femenino,Urbano,Ambulatorio,Mar-19,4,2,Alta,...,0,0,0,0,0,0,0,2019-03-31,2019-04-03,2

"Se ha agregado una columna que indica si la persona ha reingresado, según el análisis de su historial de admisiones.

In [95]:
df['Reingreso'] = np.where(df['Nro de Ingresos'] > 1, 'Si', 'No')

#EDA